# ==============================================================
# PARÁMETROS POBLACIONALES
# ==============================================================
NUM_PACIENTES = 412
PROPORCION_MED = 102 / NUM_PACIENTES
PROPORCION_LOW_FAT = 110 / NUM_PACIENTES
PROPORCION_KETO = 100 / NUM_PACIENTES
PROPORCION_VEGETARIANA = 100 / NUM_PACIENTES

# Tasas de abandono
TASA_ABANDONO_MED = 0.137
TASA_ABANDONO_LOW_FAT = 0.263

# Edad (años)
EDAD_MEDIA = 51.0
EDAD_STD = 10.5

# Probabilidades género
PROPORCION_MUJERES_MED = 0.58
PROPORCION_MUJERES_LOW_FAT = 0.605

# Factor de conversión de Kj a Kcal
KJ_TO_KCAL = 4.184


# ==============================================================
# DIETA MEDITERRÁNEA
# ==============================================================

# 1. Ingesta nutricional DIARIA (medias y desviaciones estándar)

# Energía total diaria (Kcal)
ENERGIA_MEDIA_MED_INICIAL = 8471.2 / KJ_TO_KCAL
ENERGIA_STD_MED_INICIAL = 2406.8 / KJ_TO_KCAL

DEFICIT_MEDIA_MED = 2190 / KJ_TO_KCAL

# Proteínas (% de enería)
PROT_PCT_MEDIA_MED_INICIAL = 0.184      
PROT_PCT_STD_MED_INICIAL = 0.035 

PROT_PCT_MEDIA_MED = 0.196
PROT_PCT_STD_MED = 0.032

# Carbohidratos (% de energía)
CARB_PCT_MEDIA_MED_INICIAL = 0.426      
CARB_PCT_STD_MED_INICIAL = 0.061        

CARB_PCT_MEDIA_MED = 0.458
CARB_PCT_STD_MED = 0.051

# Grasa total (% de energía)
GRASA_PCT_MEDIA_MED_INICIAL = 0.390     
GRASA_PCT_STD_MED_INICIAL = 0.061       

GRASA_PCT_MEDIA_MED = 0.346
GRASA_PCT_STD_MED = 0.069

# Grasa saturada (% de energía)
GRASA_SAT_PCT_MEDIA_MED_INICIAL = 0.144 / GRASA_PCT_MEDIA_MED_INICIAL
GRASA_SAT_PCT_STD_MED_INICIAL = 0.037

GRASA_SAT_PCT_MEDIA_MED = 0.100 / GRASA_PCT_MEDIA_MED
GRASA_SAT_PCT_STD_MED = 0.026

# Grasa monoinsaturada (% de energía)
GRASA_MONO_PCT_MEDIA_MED_INICIAL = 0.143 / GRASA_PCT_MEDIA_MED_INICIAL
GRASA_MONO_PCT_STD_MED_INICIAL = 0.033

GRASA_MONO_PCT_MEDIA_MED = 0.156 / GRASA_PCT_MEDIA_MED
GRASA_MONO_PCT_STD_MED = 0.039

# Grasa poliinsaturada (% de energía)
GRASA_POLI_PCT_MEDIA_MED_INICIAL = 0.054 / GRASA_PCT_MEDIA_MED_INICIAL
GRASA_POLI_PCT_STD_MED_INICIAL = 0.022

GRASA_POLI_PCT_MEDIA_MED = 0.058 / GRASA_PCT_MEDIA_MED
GRASA_POLI_PCT_STD_MED = 0.022

# Fibra soluble (g)
FIBRA_SOLUBLE_MEDIA_MED_INICIAL = 4.3
FIBRA_SOLUBLE_STD_MED_INICIAL = 2.1

MEAN_CHANGE_FIBRA_SOLUBLE_MED = 0.6

# Colesterol dietético (mg)
COL_DIETETICO_MEDIA_MED_INICIAL = 311.7
COL_DIETETICO_STD_MED_INICIAL = 138.6

MEAN_CHANGE_COL_DIETETICO_MED = -131.5


# 2. Biomarcadores inciales (medias y desviaciones estándar)
# Colesterol total (mmol/L)
COL_TOTAL_MEDIA_MED = 6.6
COL_TOTAL_STD_MED = 1.0

# Colesterol LDL "malo" (mmol/L)
COL_LDL_MEDIA_MED = 4.4
COL_LDL_STD_MED = 1.0


# ==============================================================
# DIETA BAJA EN GRASAS
# ==============================================================

# 1. Ingesta nutricional DIARIA (medias y desviaciones estándar)
# Energía total diaria (Kcal)
ENERGIA_MEDIA_LOW_FAT_INICIAL = 8489.5 / KJ_TO_KCAL
ENERGIA_STD_LOW_FAT_INICIAL = 2875.4 / KJ_TO_KCAL

DEFICIT_MEDIA_LOW_FAT = 2081 / KJ_TO_KCAL

# Proteínas (% de energía) 
PROT_PCT_MEDIA_LOW_FAT_INICIAL = 0.194  
PROT_PCT_STD_LOW_FAT_INICIAL = 0.040

PROT_PCT_MEDIA_LOW_FAT = 0.213
PROT_PCT_STD_LOW_FAT = 0.036

# Carbohidratos (% de energía)
CARB_PCT_MEDIA_LOW_FAT_INICIAL = 0.416  
CARB_PCT_STD_LOW_FAT_INICIAL = 0.071

CARB_PCT_MEDIA_LOW_FAT = 0.448
CARB_PCT_STD_LOW_FAT = 0.067

# Grasa total (% de energía)
GRASA_PCT_MEDIA_LOW_FAT_INICIAL = 0.390     
GRASA_PCT_STD_LOW_FAT_INICIAL = 0.069       

GRASA_PCT_MEDIA_LOW_FAT = 0.339
GRASA_PCT_STD_LOW_FAT = 0.064

# Grasa saturada (% de energía)
GRASA_SAT_PCT_MEDIA_LOW_FAT_INICIAL = 0.143 / GRASA_PCT_MEDIA_LOW_FAT_INICIAL
GRASA_SAT_PCT_STD_LOW_FAT_INICIAL = 0.037

GRASA_SAT_PCT_MEDIA_LOW_FAT = 0.103 / GRASA_PCT_MEDIA_LOW_FAT
GRASA_SAT_PCT_STD_LOW_FAT = 0.031

# Grasa monoinsaturada (% de energía)
GRASA_MONO_PCT_MEDIA_LOW_FAT_INICIAL = 0.144 / GRASA_PCT_MEDIA_LOW_FAT_INICIAL
GRASA_MONO_PCT_STD_LOW_FAT_INICIAL = 0.032

GRASA_MONO_PCT_MEDIA_LOW_FAT = 0.134 / GRASA_PCT_MEDIA_LOW_FAT
GRASA_MONO_PCT_STD_LOW_FAT = 0.032

# Grasa poliinsaturada (% de energía)
GRASA_POLI_PCT_MEDIA_LOW_FAT_INICIAL = 0.054 / GRASA_PCT_MEDIA_LOW_FAT_INICIAL
GRASA_POLI_PCT_STD_LOW_FAT_INICIAL = 0.019

GRASA_POLI_PCT_MEDIA_LOW_FAT = 0.063 / GRASA_PCT_MEDIA_LOW_FAT
GRASA_POLI_PCT_STD_LOW_FAT = 0.027

# Fibra soluble (g)
FIBRA_SOLUBLE_MEDIA_LOW_FAT_INICIAL = 4.0
FIBRA_SOLUBLE_STD_LOW_FAT_INICIAL = 1.9

MEAN_CHANGE_FIBRA_SOLUBLE_LOW_FAT = 0.4

# Colesterol dietético (mg)
COL_DIETETICO_MEDIA_LOW_FAT_INICIAL = 338.6
COL_DIETETICO_STD_LOW_FAT_INICIAL = 158.7

MEAN_CHANGE_COL_DIETETICO_LOW_FAT = -139.3


# 2. Biomarcadores inciales (medias y desviaciones estándar)
# Colesterol total (mmol/L)
COL_TOTAL_MEDIA_LOW_FAT = 6.4
COL_TOTAL_STD_LOW_FAT = 0.9

# Colesterol LDL "malo" (mmol/L)
COL_LDL_MEDIA_LOW_FAT = 4.1
COL_LDL_STD_LOW_FAT = 0.9


# ==============================================================
# DIETA KETO
# ==============================================================

# 1. Ingesta nutricional DIARIA (medias y desviaciones estándar)
# Energía total diaria (Kcal)
ENERGIA_MEDIA_KETO_INICIAL = 2000
ENERGIA_STD_KETO_INICIAL = 631.1

DEFICIT_MEDIA_KETO = 500

# Proteínas (% de energía)
PROT_PCT_MEDIA_KETO_INICIAL = 0.189
PROT_PCT_STD_KETO_INICIAL = 0.0375

PROT_PCT_MEDIA_KETO = 0.20
PROT_PCT_STD_KETO = 0.034

# Carbohidratos (% de energía)
CARB_PCT_MEDIA_KETO_INICIAL = 0.421
CARB_PCT_STD_KETO_INICIAL = 0.066

CARB_PCT_MEDIA_KETO = 0.05
CARB_PCT_STD_KETO = 0.005

# Grasa total (% de energía)
GRASA_PCT_MEDIA_KETO_INICIAL = 0.39
GRASA_PCT_STD_KETO_INICIAL = 0.065

GRASA_PCT_MEDIA_KETO = 0.75
GRASA_PCT_STD_KETO = 0.0665

# Grasa saturada (% de energía)
GRASA_SAT_PCT_MEDIA_KETO_INICIAL = 0.144 / GRASA_PCT_MEDIA_KETO_INICIAL
GRASA_SAT_PCT_STD_KETO_INICIAL = 0.037

GRASA_SAT_PCT_MEDIA_KETO = 0.3 / GRASA_PCT_MEDIA_KETO
GRASA_SAT_PCT_STD_KETO = 0.028

# Grasa monoinsaturada (% de energía)
GRASA_MONO_PCT_MEDIA_KETO_INICIAL = 0.143 / GRASA_PCT_MEDIA_KETO_INICIAL
GRASA_MONO_PCT_STD_KETO_INICIAL = 0.032

GRASA_MONO_PCT_MEDIA_KETO = 0.3375 / GRASA_PCT_MEDIA_KETO
GRASA_MONO_PCT_STD_KETO = 0.035

# Grasa poliinsaturada (% de energía)
GRASA_POLI_PCT_MEDIA_KETO_INICIAL = 0.054 / GRASA_PCT_MEDIA_KETO_INICIAL
GRASA_POLI_PCT_STD_KETO_INICIAL = 0.02

GRASA_POLI_PCT_MEDIA_KETO = 0.075 / GRASA_PCT_MEDIA_KETO
GRASA_POLI_PCT_STD_KETO = 0.025

# Fibra soluble (g)
FIBRA_SOLUBLE_MEDIA_KETO_INICIAL = 4.1
FIBRA_SOLUBLE_STD_KETO_INICIAL = 2.0

MEAN_CHANGE_FIBRA_SOLUBLE_KETO = -2.0

# Colesterol dietético (mg)
COL_DIETETICO_MEDIA_KETO_INICIAL = 320.0
COL_DIETETICO_STD_KETO_INICIAL = 150.0

MEAN_CHANGE_COL_DIETETICO_KETO = 130.0

# 2. Biomarcadores inciales (medias y desviaciones estándar)
# Colesterol total (mmol/L)
COL_TOTAL_MEDIA_KETO = 6.5
COL_TOTAL_STD_KETO = 1.0

# Colesterol LDL "malo" (mmol/L)
COL_LDL_MEDIA_KETO = 4.2
COL_LDL_STD_KETO = 1.0


# ==============================================================
# DIETA VEGETARIANA
# ==============================================================

# 1. Ingesta nutricional DIARIA (medias y desviaciones estándar)
# Energía total diaria (Kcal)
ENERGIA_MEDIA_VEGETARIANA_INICIAL = 2000
ENERGIA_STD_VEGETARIANA_INICIAL = 631.1

DEFICIT_MEDIA_VEGETARIANA = 500

# Proteínas (% de energía)
PROT_PCT_MEDIA_VEGETARIANA_INICIAL = 0.189
PROT_PCT_STD_VEGETARIANA_INICIAL = 0.0375

PROT_PCT_MEDIA_VEGETARIANA = 0.15
PROT_PCT_STD_VEGETARIANA = 0.020

# Carbohidratos (% de energía)
CARB_PCT_MEDIA_VEGETARIANA_INICIAL = 0.421
CARB_PCT_STD_VEGETARIANA_INICIAL = 0.066

CARB_PCT_MEDIA_VEGETARIANA = 0.765
CARB_PCT_STD_VEGETARIANA = 0.059

# Grasa total (% de energía)
GRASA_PCT_MEDIA_VEGETARIANA_INICIAL = 0.39
GRASA_PCT_STD_VEGETARIANA_INICIAL = 0.065

GRASA_PCT_MEDIA_VEGETARIANA = 0.085
GRASA_PCT_STD_VEGETARIANA = 0.005

# Grasa saturada (% de energía)
GRASA_SAT_PCT_MEDIA_VEGETARIANA_INICIAL = 0.144 / GRASA_PCT_MEDIA_VEGETARIANA_INICIAL
GRASA_SAT_PCT_STD_VEGETARIANA_INICIAL = 0.037

GRASA_SAT_PCT_MEDIA_VEGETARIANA = 0.03 / GRASA_PCT_MEDIA_VEGETARIANA
GRASA_SAT_PCT_STD_VEGETARIANA = 0.0018

# Grasa monoinsaturada (% de energía)
GRASA_MONO_PCT_MEDIA_VEGETARIANA_INICIAL = 0.143 / GRASA_PCT_MEDIA_VEGETARIANA_INICIAL
GRASA_MONO_PCT_STD_VEGETARIANA_INICIAL = 0.032 

GRASA_MONO_PCT_MEDIA_VEGETARIANA = 0.0375 / GRASA_PCT_MEDIA_VEGETARIANA
GRASA_MONO_PCT_STD_VEGETARIANA = 0.002

# Grasa poliinsaturada (% de energía)
GRASA_POLI_PCT_MEDIA_VEGETARIANA_INICIAL = 0.054 / GRASA_PCT_MEDIA_VEGETARIANA_INICIAL
GRASA_POLI_PCT_STD_VEGETARIANA_INICIAL = 0.02

GRASA_POLI_PCT_MEDIA_VEGETARIANA = 0.0175 / GRASA_PCT_MEDIA_VEGETARIANA
GRASA_POLI_PCT_STD_VEGETARIANA = 0.0015

# Fibra soluble (g)
FIBRA_SOLUBLE_MEDIA_VEGETARIANA_INICIAL = 4.1
FIBRA_SOLUBLE_STD_VEGETARIANA_INICIAL = 2.0

MEAN_CHANGE_FIBRA_SOLUBLE_VEGETARIANA = 6.0

# Colesterol dietético (mg)
COL_DIETETICO_MEDIA_VEGETARIANA_INICIAL = 320.0
COL_DIETETICO_STD_VEGETARIANA_INICIAL = 150.0

MEAN_CHANGE_COL_DIETETICO_VEGETARIANA = -301.4

# 2. Biomarcadores inciales (medias y desviaciones estándar)
# Colesterol total (mmol/L)
COL_TOTAL_MEDIA_VEGETARIANA = 6.5
COL_TOTAL_STD_VEGETARIANA = 1.0

# Colesterol LDL "malo" (mmol/L)
COL_LDL_MEDIA_VEGETARIANA = 4.2
COL_LDL_STD_VEGETARIANA = 1.0